### PR TITLE
Enabled the generation of documentation files

### PR DESCRIPTION
**Pull request by randym32**
Enabled a checkbox in the project settings that creates the XML documentation for the inline comments that is used to provide the documentation in the assembly.

### CODE REVIEW

**Review by alanedwardes — CHANGES_REQUESTED** [review]
This is a hardcoded path so won't work - you just need to add
```
<GenerateDocumentationFile>true</GenerateDocumentationFile>
```

into the first `<PropertyGroup>` section (underneath `<TargetFramework>netstandard2.0</TargetFramework>` for example)

**Comment by randym32** [comment]
Good catch! I  wish the ticked a box made it project relative

**Review by alanedwardes — APPROVED** [review]

**Comment by alanedwardes** [comment]
@randym32 was there another PR coming, or should I push a new minor version of the package to NuGet?

**Comment by randym32** [comment]
Yes, I intend to submit two more “nice to have” PRs -- I had to take a break to do the day job.


> On Mar 5, 2021, at 10:17 AM, Alan Edwardes <notifications@github.com> wrote:
> 
> 
> @randym32 was there another PR coming, or should I push a new minor version of the package to NuGet?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Randy
 — Sent unencumbered by the thought process

**Pull request merged**
